#!/bin/bash

# Reattach to unattached sessions as long as they exist

iteration=0

get_unattached() {
    tmux list-sess | grep -v '\(attached\)' | awk -F":" '{print $1}' | head -n 1
}

while [ 1 ] ; do
    unattached=$(get_unattached)

    if [[ "${iteration}" == "0" ]] ; then
	if [[ "${unattached}" == "" ]] ; then
	    # New session
	    tmux
	    unattached=$(get_unattached)
	fi
    fi

    if [[ "${unattached}" != "" ]] ; then
	# Attach to session
	tmux a -t ${unattached}
    else
	# No more sessions
	break
    fi

    iteration=$(($iteration + 1))
done
